// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOar9liFVkN-5rgVBjsiuxq_ZAPHlxb38',
    appId: '1:390267550791:web:69a72a0f0691e426760562',
    messagingSenderId: '390267550791',
    projectId: 'inclass16-32666',
    authDomain: 'inclass16-32666.firebaseapp.com',
    storageBucket: 'inclass16-32666.firebasestorage.app',
    measurementId: 'G-TPNNSDY8LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0RShsxskzKDPSxcs_r8Czq_3mLIOaOAA',
    appId: '1:390267550791:android:f9c37819fab6210e760562',
    messagingSenderId: '390267550791',
    projectId: 'inclass16-32666',
    storageBucket: 'inclass16-32666.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBHmMMwYSjnlpd-EHfYPXUOr__1mj5ouK4',
    appId: '1:390267550791:ios:5726a2a57bd13272760562',
    messagingSenderId: '390267550791',
    projectId: 'inclass16-32666',
    storageBucket: 'inclass16-32666.firebasestorage.app',
    iosBundleId: 'com.example.inc16',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBHmMMwYSjnlpd-EHfYPXUOr__1mj5ouK4',
    appId: '1:390267550791:ios:5726a2a57bd13272760562',
    messagingSenderId: '390267550791',
    projectId: 'inclass16-32666',
    storageBucket: 'inclass16-32666.firebasestorage.app',
    iosBundleId: 'com.example.inc16',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDOar9liFVkN-5rgVBjsiuxq_ZAPHlxb38',
    appId: '1:390267550791:web:79812685d3bb4dfe760562',
    messagingSenderId: '390267550791',
    projectId: 'inclass16-32666',
    authDomain: 'inclass16-32666.firebaseapp.com',
    storageBucket: 'inclass16-32666.firebasestorage.app',
    measurementId: 'G-8SRP90EFNB',
  );
}
